### ISSUE TITLE
3.3.2 build error

### ISSUE THREAD

**Issue by christian1combo** [OpenFlutter/flutter_oktoast#102]
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
../../../../.pub-cache/hosted/pub.flutter-io.cn/oktoast-3.3.2/lib/src/widget/overlay.dart:582:9:
Error: A constant constructor can't call a non-constant super constructor.

**Comment by RuberDucky** [comment]
Same error I also got, how can we debug it?

**Comment by AlexV525** [comment]
Which Flutter version?

**Comment by RuberDucky** [comment]
It's 3.7 on Mac now. I will try this on the Windows 3.10 version.

**Comment by AlexV525** [comment]
Ran some blame and found the cause: https://github.com/flutter/flutter/pull/119195.
