### ISSUE TITLE
ToastPosition的offset貌似没有作用

### ISSUE THREAD

**Issue by caiyoufei** [OpenFlutter/flutter_oktoast#13]
![image](https://user-images.githubusercontent.com/11989916/52174580-fcd4dc00-27d0-11e9-9623-7be79051b2a0.png)

**Comment by caiyoufei** [comment]
打印能看到设置成功了offset的值，但是在手机上吐司的时候没有

**Comment by CaiJingLong** [comment]
I may have to wait for the Spring Festival before I have time to repair it.
