### ISSUE TITLE
Toast displayed on main page only

### ISSUE THREAD

**Issue by Xihuny** [OpenFlutter/flutter_oktoast#18]
I have multiple pages in my app. The problem is Toast is showing only on the main page, even if I call `showToastWidget(...)` from any other pages. Please have a look at my code below

**Page 1 - Main Page**
```  @override
  Widget build(BuildContext context) {
    return OKToast(
      child: Scaffold(
        backgroundColor: Theme.of(context).accentColor,
        body: Center(
          child: SizedBox(
            height: 50,
            width: 50,
            child: Image(image: AssetImage('assets/ic_logo.png')),
          ),
        ),
      ),
    );
  }```

**Page 2**
```  @override
  Widget build(BuildContext context) {
    return OKToast(
      child: Scaffold(
        appBar: AppBar(
          centerTitle: true,
          title: Text('Page2'),
        ),
        body: ...
);```

**Comment by CaiJingLong** [comment]
See [Readme](https://github.com/OpenFlutter/flutter_oktoast#3-wrap-your-app-widget)

You don't need to wrap `Scaffold` of every page, you just need to wrap your `MaterialApp`.(`WidgetsApp` or `CupertinoApp`).

**Comment by CaiJingLong** [comment]
https://github.com/OpenFlutter/flutter_oktoast/blob/35af283d599e2650ead5b5670bf75f6b8858939d/example/main.dart#L11

**Comment by Xihuny** [comment]
Yes. My mistake. I wasn't editing the main.dart file

**Comment by dotcink** [comment]
> See [Readme](https://github.com/OpenFlutter/flutter_oktoast#3-wrap-your-app-widget)
> 
> You don't need to wrap `Scaffold` of every page, you just need to wrap your `MaterialApp`.(`WidgetsApp` or `CupertinoApp`).

However, with this, `Image.asset()`will be unable to use 2x 3x images.
