### ISSUE TITLE
how to respond to click events

### ISSUE THREAD

**Issue by jefferybai** [OpenFlutter/flutter_oktoast#19]
I added a click event but did not respond

**Comment by CaiJingLong** [comment]
Toast generally does not allow capture of touch events
So this library has not supported click events since its inception.

**Comment by jefferybai** [comment]
如果是这样我干嘛不用showCupertinoDialog

**Comment by CaiJingLong** [comment]
Toast was designed that way, it is a weak tip and should not interrupt the user's flow of operations.
And toast should not be used if you need to be able to respond to user clicks.

I'm talking about Toast, not just `OKToast`.

----

So, if you need to interrupt user actions and respond to click events, use dialog or Overlay

**Comment by noobiek** [comment]
Hello, CaiJingLong!

Thank you for the great plugin! Thanks to people like you - everyone saves a lot of time.

About toast taps. Still, would be great to be able to intercept toast taps. It is not about interrupting user's flow, but rather user may **choose** to respond to the toast's info. For example, a "you have a new message in chat with UserX" notification appears, then user may choose to tap it and be transfered to the respective chat with UserX window. It is not a toast, but rather notificaton functionality, I agree. But your plugin would make it easy to implement both behaviours.

**Comment by CaiJingLong** [comment]
According to the two suggestions, I implemented support for click events in 2.2.0.
The default value is false, but the `handleTouch` property can be set to true to support click events.
