### ISSUE TITLE
暴露出context是否有意义？

### ISSUE THREAD

**Issue by HannibalKcc** [OpenFlutter/flutter_oktoast#20]
我是新学flutter的，对于获取 `context` 用以在 `dio` 拦截器做全局 `Loading` 或 `Toast` 已经困扰几天了.

看到作者获取 context 的方法后很是佩服，我觉得获得一个在任意时候可用的 `context` 很有用，希望能在源码中把 `_contextMap` 暴露出来，这样使用者可以更方便地使用。（当然，也许只有我一个人这么认为）

不知作者怎么想？

**Comment by CaiJingLong** [comment]
这个包原则上不会暴露这个全局的context,但是你可以fork后自己来做这件事,然后使用git依赖的方式
https://dart.dev/tools/pub/dependencies#git-packages

缓存全局的context,我虽然这么做了, 但不一定是好想法,这个东西见仁见智吧

建议你如果有这样的需求还是自己写一个包比较好, 另外网络请求时如果需要dialog框也可以借助原生实现
