### ISSUE TITLE
在 release 运行模式下，showToast不能弹出

### ISSUE THREAD

**Issue by HZRZCW** [OpenFlutter/flutter_oktoast#24]
在 release 运行模式下，showToast不能弹出！

**Comment by CaiJingLong** [comment]
OKToast is a pure dart library, it hasn't any native code.
So release mode has no effect on OKToast.

Please try to rerun. 

If you're sure there's a problem, please provide a minimum runnable code and reproducible steps.

**Comment by CaiJingLong** [comment]
I will close this issue. 
If you are sure there is a bug and you can submit minimum runnable code, please re-open and submit code.
