### ISSUE TITLE
OKToast 配置 dismissOtherOnShow无效

### ISSUE THREAD

**Issue by simplezhli** [OpenFlutter/flutter_oktoast#28]
问题代码在 https://github.com/OpenFlutter/flutter_oktoast/blob/master/lib/src/toast.dart#L238 

修复：
```dart

dismissOtherToast = _ToastTheme.of(context).dismissOtherOnShow ?? false;

```

**Comment by CaiJingLong** [comment]
What are the specific problems?

**Comment by simplezhli** [comment]
在OKToast 中设置dismissOtherOnShow为true，但是没有生效。看了下代码，找到了问题代码。

**Comment by simplezhli** [comment]
`dismissOtherToast` 默认为false  ，那么`dismissOtherToast??` 肯定是false了，`_ToastTheme.of(context).dismissOtherOnShow ??`的判断都不会进

**Comment by CaiJingLong** [comment]
![image](https://user-images.githubusercontent.com/14145407/60692809-5c631f00-9f0a-11e9-9d39-75a65aac19e8.png)

If you haven't set parameters, the bool type defaults to null rather than false.

**Comment by CaiJingLong** [comment]
https://github.com/OpenFlutter/flutter_oktoast/blob/50338b7fd81315979e74ece00fd77388273cf6d3/lib/src/toast.dart#L148

Your problem maybe is the line. 
This parameter is false by default because it is compatible with previous behavior. In the next version, I will delete this default value to make it more semantically compatible.

**Comment by simplezhli** [comment]
![image](https://user-images.githubusercontent.com/12456431/60693104-8406b700-9f0b-11e9-857f-71916211704e.png)

大致意思如图，对应代码：https://github.com/OpenFlutter/flutter_oktoast/blob/master/lib/src/toast.dart#L238

**Comment by CaiJingLong** [comment]
The latest version is change the dismissOtherToast default value.
The `dismissOtherToast` will follow the order of showToast => OKToast config.

Update version to 2.2.0 can see the change.
