### ISSUE TITLE
突然不能用了 

### ISSUE THREAD

**Issue by gzpaiwxc** [OpenFlutter/flutter_oktoast#29]
大佬 , 我之前写的 demo 上用的好好的 , 突然不能用了 , 不能弹吐司,报了如下错误:
![OG0 G15H$@DOREESUB2} 58](https://user-images.githubusercontent.com/16586195/60708948-d367da00-9f41-11e9-84da-73ab92351074.png)

下面的代码也没写错什么呀 , 大佬 , 能否看下什么问题 ?

![1562315742(1)](https://user-images.githubusercontent.com/16586195/60709435-fe066280-9f42-11e9-8ac6-d503963c99e9.jpg)

![O1XF($XT7CLSRU}VY9E%T1T](https://user-images.githubusercontent.com/16586195/60709202-7a4c7600-9f42-11e9-8087-8ab8ece64f1f.png)

![1562315647(1)](https://user-images.githubusercontent.com/16586195/60709363-d0211e00-9f42-11e9-9b36-0365d078cd4f.jpg)

**Comment by CaiJingLong** [comment]
The params of `duration` is `Duration`, not int.

**Comment by gzpaiwxc** [comment]
@CaiJingLong  源码上面的 duration 里的参数都是 int 类型
![1562315866(1)](https://user-images.githubusercontent.com/16586195/60709574-5e959f80-9f43-11e9-82f6-b9ac21cef2eb.jpg)

**Comment by CaiJingLong** [comment]
Please provide a example to show the problem.
Gist , code or repository can be support.
