### ISSUE TITLE
不能弹出提示 错误如下

### ISSUE THREAD

**Issue by oh-jy** [OpenFlutter/flutter_oktoast#32]
I/flutter ( 8069): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 8069): The following NoSuchMethodError was thrown while handling a gesture:
I/flutter ( 8069): The getter 'inMilliseconds' was called on null.
I/flutter ( 8069): Receiver: null
I/flutter ( 8069): Tried calling: inMilliseconds
I/flutter ( 8069):
I/flutter ( 8069): When the exception was thrown, this was the stack:
I/flutter ( 8069): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
I/flutter ( 8069): #6      showToastWidget 
package:oktoast/…/core/toast.dart:138
I/flutter ( 8069): #7      showToast 
package:oktoast/…/core/toast.dart:71

  showToastWidget line 138 
  Future.delayed(duration, () {
    future.dismiss();
  });

**Comment by CaiJingLong** [comment]
Duration must be not null.

**Comment by oh-jy** [comment]
thanks 希望能把 duration 加上个required...看到源码里面有_defaultDuration 所以就没有传入

**Comment by CaiJingLong** [comment]
This parameter has a default value, you don't have to pass in. But if you pass in, the duration can't be null.
