### ISSUE TITLE
华为mate30 手机弹出框无法显示AST

### ISSUE THREAD

**Issue by winnxiegang** [OpenFlutter/flutter_oktoast#37]

**Comment by winnxiegang** [comment]
/// useName组件
  Widget _usePhoneWidget() {
    return Container(
      child: Row(
        children: <Widget>[
          Text(
            '密码',
            style: TextstyleUtils.LoginText,
          ),
          SizedBox(width: 10),
          Flexible(
            child: TextField(
             keyboardType: TextInputType.phone,//输入方式为密码 输入法弹出 有toast
              onChanged: (text) {
                //内容改变的回调
                ProviderUtils.Pro<LoginProvide>(context)?.setUsePhone('$text');
              },
              obscureText: true,
              decoration: InputDecoration(
                hintText: '请输入密码',
              ),
            ),
          )
        ],
      ),
    );
  }
}

**Comment by CaiJingLong** [comment]
Any log?

**Comment by CaiJingLong** [comment]
I don't know your problem. So I will close it.

If you have change of it. Please reopen the issue.
