### ISSUE TITLE
textAlign 用法

### ISSUE THREAD

**Issue by lichenbuliren** [OpenFlutter/flutter_oktoast#38]
通过查看源码发现，`textAlign = _ToastTheme.of(context).textAlign;` 取的是 `context` 的，不清楚这里设计的目的是什么，为啥不通过构造参数直接读取，还是说这里是漏掉了 `textAlign ??= _ToastTheme.of(context).textAlign;`

**Comment by CaiJingLong** [comment]
I think this is bug.😃

**Comment by CaiJingLong** [comment]
I fixed it in [showtoast-text-align-problem](https://github.com/OpenFlutter/flutter_oktoast/tree/showtoast-text-align-problem) 3 month ago.
But I forgot to merge code to master. 

Thanks for issue.

**Comment by CaiJingLong** [comment]
Fixed it in #41 .
