### ISSUE TITLE
文字下面出现两个黄色的下划线

### ISSUE THREAD

**Issue by jlcool** [OpenFlutter/flutter_oktoast#4]

**Comment by CaiJingLong** [comment]
Provide a running sample code

**Comment by jlcool** [comment]
OKToast(
      child: Scaffold()
)
OKToast写在Scaffold前面会有这个问题，写在MaterialApp前面没问题

**Comment by CaiJingLong** [comment]
So you need is a page-level Toast?
Get it. 

TODO : support page level.

**Comment by CaiJingLong** [comment]
fix it.
see #5 
update version to 2.0.1
