### ISSUE TITLE
主APP入口是StoreProvider 的情况下，怎么使用

### ISSUE THREAD

**Issue by muziling** [OpenFlutter/flutter_oktoast#45]
我的代码入口是 StoreProvider ，怎么用 oktoast
class MyApp extends StatelessWidget {
  final Store<ReduxState> store;

  MyApp({this.store});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return StoreProvider<ReduxState>(
        store: store,
        child: MaterialApp(
          debugShowCheckedModeBanner: false,
          theme: ThemeData(

**Comment by CaiJingLong** [comment]
Wrap StoreProvider or MaterialApp.
