### ISSUE TITLE
Error on double tap in TextFormField

### ISSUE THREAD

**Issue by jjvillavicencio** [OpenFlutter/flutter_oktoast#46]
`I/flutter (10337): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (10337): The following assertion was thrown building
I/flutter (10337): _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#35d2a](dirty, state:
I/flutter (10337): _OverlayEntryWidgetState#42386):
I/flutter (10337): No MediaQuery widget found.
I/flutter (10337): _OverlayEntryWidget widgets require a MediaQuery widget ancestor.
I/flutter (10337): The specific widget that could not find a MediaQuery ancestor was:
I/flutter (10337):   _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#35d2a]
I/flutter (10337): The ownership chain for the affected widget is:
I/flutter (10337):   "_OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#35d2a] ← _Theatre ← Overlay ←
I/flutter (10337):   Directionality ← _ToastTheme ← OKToast ← DynamicTheme ← MyApp ← [root]"
I/flutter (10337): Typically, the MediaQuery widget is introduced by the MaterialApp or WidgetsApp widget at the top of
I/flutter (10337): your application widget tree.
I/flutter (10337):
I/flutter (10337): The relevant error-causing widget was:
I/flutter (10337):   Overlay
I/flutter (10337):   
../…/widget/oktoast.dart:86
I/flutter (10337):`

> ../…/widget/oktoast.dart:86

`
  @override
  Widget build(BuildContext context) {
    var overlay = Overlay(
      initialEntries: [
        OverlayEntry(
          builder: (ctx) {
            _contextMap[this] = ctx;
            return widget.child;
          },
        ),
      ],
    );`

**Comment by MoacirSchmidt** [comment]
Same occurs in flutter web! (double tap in TextField with multiLine:true)

![image](https://user-images.githubusercontent.com/15182027/73798774-ae1aa300-4792-11ea-9b3c-5e24e534eebc.png)

**Comment by CaiJingLong** [comment]
How to reproduce?

**Comment by MoacirSchmidt** [comment]
here you have a case:

https://github.com/MoacirSchmidt/mq_not_found

just double tap (on device) or double click (on emulator) to see the message (no problem on flutter web)!

Thank you very much for your excellent package!
