### ISSUE TITLE
关闭自身调用dismiss无效, 怎么解决?

### ISSUE THREAD

**Issue by cander0815** [OpenFlutter/flutter_oktoast#50]
代码如下: 
```

class Loading {
  ToastFuture a;
  static final Loading _singleton = Loading._internal();

  static Loading get instance => Loading();

  factory Loading() {
    return _singleton;
  }

  Loading._internal() {}

  show({String title = ''}) {
    print('显示loading');
    a = showToastWidget(
      LoadingDialog(
        text: title,
      ),
      duration: Duration(seconds: 20),
    );
  }

  hide() {
    print('隐藏loading $a');
    a?.dismiss();
    a = null;
  }
}

```

调用后不会隐藏当前的loading, 而是要20s后自己隐藏;

**Comment by CaiJingLong** [comment]
I test have no problem.

my code:

<details>

main.dart
```dart
import 'package:flutter/material.dart';
import 'package:oktoast/oktoast.dart';

import 'loading.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return OKToast(
      child: MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          // This is the theme of your application.
          //
          // Try running your application with "flutter run". You'll see the
          // application has a blue toolbar. Then, without quitting the app, try
          // changing the primarySwatch below to Colors.green and then invoke
          // "hot reload" (press "r" in the console where you ran "flutter run",
          // or simply save your changes to "hot reload" in a Flutter IDE).
          // Notice that the counter didn't reset back to zero; the application
          // is not restarted.
          primarySwatch: Colors.blue,
        ),
        home: MyHomePage(title: 'Flutter Demo Home Page'),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() async {
    final loading = Loading();
    loading.show();

    await Future.delayed(Duration(seconds: 2));
    loading.hide();
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

loading.dart:

```dart
import 'package:flutter/material.dart';
import 'package:oktoast/oktoast.dart';

class Loading {
  ToastFuture a;
  static final Loading _singleton = Loading._internal();

  static Loading get instance => Loading();

  factory Loading() {
    return _singleton;
  }

  Loading._internal() {}

  show({String title = ''}) {
    print('显示loading');
    a = showToastWidget(
      LoadingDialog(),
      duration: Duration(seconds: 20),
    );
  }

  hide() {
    print('隐藏loading $a');
    a?.dismiss();
    a = null;
  }
}

class LoadingDialog extends StatefulWidget {
  @override
  _LoadingDialogState createState() => _LoadingDialogState();
}

class _LoadingDialogState extends State<LoadingDialog> {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: SizedBox.fromSize(
        size: Size.square(40),
        child: CircularProgressIndicator(),
      ),
    );
  }
}

```

</details>

**Comment by cander0815** [comment]
> 我测试没有问题。
> 
> 我的代码：
> 
> 主镖
> 
> ```dart
> 导入 'package：flutter / material.dart' ;
> 导入 'package：oktoast / oktoast.dart' ; 导入'loading.dart' ; void main（）= > runApp（MyApp（））; 类MyApp 扩展了StatelessWidget {
>    //此小部件是应用程序的根。@override Widget build（BuildContext context）{
>      return OKToast（
>       child ：MaterialApp（
>         title ：'Flutter Demo'
> 
>  
> 
>   
> 
>    
>   
>       ，
>         主题： ThemeData（
>            //这是你的应用程序的主题。
>           // 
>           //尝试运行与“扑运行”您的应用程序你会看到的。
>           //应用程序有一个蓝色的工具栏之后，无需退出应用程序，试一下。
>           //将下面的primarySwatch更改为Colors.green，然后调用
>           //“热重载”（在运行“ flutter run”的控制台中按“ r”，
>           //或简单地将更改保存到Flutter中的“ hot reload” IDE）
>            
>           。// 请注意，计数器没有重置为零；
>           // 应用程序没有重新启动。primarySwatch ： Colors .blue，
>         ），
>         主页： MyHomePage（标题： “ Flutter演示首页”），
>       ），
>     ）；
>   } 
> } 类MyHomePage 扩展了StatefulWidget {
>    MyHomePage（{ Key key，this .title}）：super（key ： key）; //此小部件是您的应用程序的主页。它是有状态的，// //它具有一个State对象（如下定义），该对象包含影响其外观的字段。//此类是状态的配置。它保存值（在此
> 
>     
> 
>   
>   
>   
> 
>   
>   //由父级提供的标题（在本例中为App小部件），
>   //由State的build方法使用。Widget子类中的字段
>   始终//标记为“最终”。
> 
>   最终的 字符串标题；@override _MyHomePageState createState（）= > _MyHomePageState（）; 
> } 类_MyHomePageState 扩展State < MyHomePage > {
>    int _counter = 0 ; void _incrementCounter（）异步 {
>      最终加载= 正在加载
> 
>   
>     
> 
>     
> 
>     （）; 
>     加载中。显示（）; 等待未来。延迟（持续时间（秒：2））；
>     加载中。隐藏（）; 
>   } @override Widget build（BuildContext上下文）{
>      //每次调用setState时都会重新运行此方法，例如，通过上面的_incrementCounter方法完成//。// // Flutter框架已经过优化，可以快速重新运行构建方法，//因此，您可以重建任何需要更新的内容，而不必单独更改小部件的实例。
> 
>       
> 
>   
>    
>     
>     
>     
>     
>     
>     回 支架（
>       appBar ： AppBar（
>          //下面我们就从被创造的MyHomePage对象的值
>         //该App.build方法，并用它来建立我们的appbar称号。 
>         标题： 文本（widget.title）， 
>       ），
>       body ： Center（
>          // Center是一个布局小部件。它接受一个孩子并将其
>         //放置在父级的中间 
>         。child ： Column（
>            // Column也是一个布局小部件。它接受一个孩子和
>           / 的列表/垂直排列它们。默认情况下，它会自动调整大小以适合其
>           //水平放置子项，并尝试使其高度与父项相同。
>           // 
>           //调用“调试绘画”（在控制台中按“ p”，
>           从Android 
>           // Studio 
>           的Flutter Inspector中选择//“ Toggle Debug Paint”操作，或在Visual Studio Code中选择“ Toggle Debug Paint”命令）//查看每个小部件的线框。
>           // 
>           //列具有各种属性，可控制其自身大小以及
>           //如何定位其子对象。这里我们使用mainAxisAlignment 
>           //将子项垂直居中；这里的主轴是垂直
>           //轴，因为列是垂直的（交叉轴
>           //是水平的）。
>           mainAxisAlignment ： MainAxisAlignment .center，
>           儿童： < 控件> [
>              文字（
>                '你按下按钮很多次：'，
>             ），文本（
>                '$ _counter '，
>               风格：主题。的（上下文）.textTheme.display1， 
>             ）
>           ]， 
>         ），
>       ）， 
>       floatingActionButton ：FloatingActionButton（
>         onPressed ： _incrementCounter，
>         提示：'增量'
>                ，
>         child ： Icon（Icons .add），
>       ），//此逗号结尾使自动格式化的构建方法更好。
>     ）; 
>   } 
> }
> ```
> 
> loading.dart：
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:oktoast/oktoast.dart';
> 
> class Loading {
>   ToastFuture a;
>   static final Loading _singleton = Loading._internal();
> 
>   static Loading get instance => Loading();
> 
>   factory Loading() {
>     return _singleton;
>   }
> 
>   Loading._internal() {}
> 
>   show({String title = ''}) {
>     print('显示loading');
>     a = showToastWidget(
>       LoadingDialog(),
>       duration: Duration(seconds: 20),
>     );
>   }
> 
>   hide() {
>     print('隐藏loading $a');
>     a?.dismiss();
>     a = null;
>   }
> }
> 
> class LoadingDialog extends StatefulWidget {
>   @override
>   _LoadingDialogState createState() => _LoadingDialogState();
> }
> 
> class _LoadingDialogState extends State<LoadingDialog> {
>   @override
>   Widget build(BuildContext context) {
>     return Center(
>       child: SizedBox.fromSize(
>         size: Size.square(40),
>         child: CircularProgressIndicator(),
>       ），
>     ）; 
>   } 
> }
> ```

请问您有试过在ios上吗?

**Comment by CaiJingLong** [comment]
This plugin is platform independent.
And I just run the code in iOS simulator.
