### ISSUE TITLE
使用Future.delay延时dismiss造成的内存泄漏

### ISSUE THREAD

**Issue by AboutJarry** [OpenFlutter/flutter_oktoast#55]
当我希望使用OKtoast来制造一个由我主动dismiss的Toast时，
我将duration设置成了极大，然后主动调用dismiss方法销毁Toast，
我创建了100万这样的toast并马上销毁，测试得出其造成的内存泄漏达到900-1200M，
我将库中的Future.delay->dismiss方法修改为用Timer实现，在Toast.dismiss方法中将Timer调用cancel并主动置null，从而避免了这个内存泄漏的问题

**Comment by CaiJingLong** [comment]
Hi, can you open pull request to fix it?

**Comment by AboutJarry** [comment]
> 
> 
> Hi, can you open pull request to fix it?

OK,I have submitted. #56
