### ISSUE TITLE
添加遮罩后点击穿透了

### ISSUE THREAD

**Issue by li305263** [OpenFlutter/flutter_oktoast#57]
Use showToastWidget method, wrap a Container and use property color.
`showToastWidget(
        Container(
          color: Colors.black.withOpacity(0.5),
          child: Center(
            child:xxxx),
          ),
        ),
      )`

**Comment by li305263** [comment]
handleTouch:true
handleTouch设置为true 就不会穿透了

**Comment by lizhuoyuan** [comment]
请问
```
handleTouch:true
```
是哪个组件的属性？

**Comment by lizhuoyuan** [comment]
> 请问
> 
> ```
> handleTouch:true
> ```
> 
> 是哪个组件的属性？

打扰了，原来是新版本加的
