### ISSUE TITLE
在异步请求前报错了

### ISSUE THREAD

**Issue by yin-shu** [OpenFlutter/flutter_oktoast#60]
我在封装底层请求时遇到的问题，望解答
![image](https://user-images.githubusercontent.com/29432662/82774925-c107cf00-9e78-11ea-9f83-79881822f985.png)

在位置1处使用时报异常如下：
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() or markNeedsBuild() called during build.
E/flutter ( 6736): This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.

在位置2正常

在位置3正常

**Comment by luoyelusheng** [comment]
加个延迟应该可以解决
`Future.delayed(const Duration(seconds: 0), () {
    showToast('9999');
  });`
建议作者在插件里面集成

**Comment by AlexV525** [comment]
尝试以下代码，并未复现。

```dart
await Future<void>.delayed(const Duration(seconds: 1));
showToast('Test');
```

**Comment by AlexV525** [comment]
在 3.1.2 版本中将 overlay 的插入行为分发到了 microtask，此问题应该已经解决。
