### ISSUE TITLE
position offset do not work when movingOnWindowChange is false

### ISSUE THREAD

**Issue by lihanst** [OpenFlutter/flutter_oktoast#63]

**Comment by 623034345** [comment]
![image](https://user-images.githubusercontent.com/21259873/92456694-d8838180-f1f5-11ea-8280-c13b0929f949.png)
![image](https://user-images.githubusercontent.com/21259873/92456718-e0432600-f1f5-11ea-8895-72f0340e0467.png)
直接报错  根本不现实

**Comment by 623034345** [comment]
════════ Exception caught by gesture ═══════════════════════════════════════════
Bad state: No element

不显示 崩

**Comment by AlexV525** [comment]
Are you still encounting this issue?

**Comment by lzw-all-in** [comment]
Yes, I'm still encountering this issue and it could because of this line of code.

https://github.com/OpenFlutter/flutter_oktoast/blob/7475ad2cfecee7d795c6a899e635c17bf626876a/lib/src/widget/container.dart#LL85C1-L106C4

**Comment by AlexV525** [comment]
> I'm very passionate to fix this issue.

Contributions are welcomed!

**Comment by lzw-all-in** [comment]
> > I'm very passionate to fix this issue.
> 
> Contributions are welcomed!

The PR will be done within today.
Thanks!
