### ISSUE TITLE
引用运行的时候报错，这个是什么情况

### ISSUE THREAD

**Issue by xhp281** [OpenFlutter/flutter_oktoast#64]
Compiler message:
Error: Could not resolve the package 'oktoast' in 'package:oktoast/oktoast.dart'.
../lib/src/ui/toast.dart:3:8: Error: Not found: 'package:oktoast/oktoast.dart'
import 'package:oktoast/oktoast.dart';

**Comment by CaiJingLong** [comment]
I think you need run 'flutter pub get' to load the package from pub server.
