### ISSUE TITLE
在TextField中长按复制文本时报错No MediaQuery widget found. The relevant error-causing widget was     OKToast 

### ISSUE THREAD

**Issue by xunzzz** [OpenFlutter/flutter_oktoast#68]
No MediaQuery widget found. 
The relevant error-causing widget was     
OKToast

**Comment by JohnJohnXia** [comment]
MaterialApp(
  builder: (context, widget) {
    return OKToast(
      child: widget,
    );
  },
);

main里用这种方式

**Comment by CaiJingLong** [comment]
This is not the first time that this problem has happened. I have answered it in https://github.com/OpenFlutter/flutter_oktoast/issues/53#issuecomment-628431625, and I have added this description to the readme.

Thank for @JohnJohnXia reply.
