### ISSUE TITLE
Flutter web -- If you don't add the toast position in flutter web, production build does not work

### ISSUE THREAD

**Issue by arualana** [OpenFlutter/flutter_oktoast#72]
I am using showToastWidget 

In flutter web, if no position is added, it works on debug mode, but for production build you get this error

```
Instance of 'minified:mJ'
main.dart.js:3962 Another exception was thrown: Instance of 'minified:eL<void>'
```

and in profile build you get these errors.

First this:

```
══╡  ╞══════════════════════════════════════════════════════════════════════════════════════════════
js_primitives.dart:47 ════════════════════════════════════════════════════════════════════════════════════════════════════
```

and then on dismissing, this

`Another exception was thrown: Instance of 'ErrorSummary'`

When adding the position, for example, `position: ToastPosition.bottom,` then the production build gets fixed

**Comment by AlexV525** [comment]
Are you still encounting this issue?
