### ISSUE TITLE
ToastPosition.bottom时会被键盘挡住

### ISSUE THREAD

**Issue by jlcool** [OpenFlutter/flutter_oktoast#8]
ToastPosition.bottom时会被键盘挡住，麻烦修改下

**Comment by CaiJingLong** [comment]
这个改不了 flutter的视图层级决定了一定会被软键盘遮挡 所以默认提示才会在中间而不是下面

**Comment by jlcool** [comment]
这我不是太懂，Scaffold 还有dialog 都不会被挡住

**Comment by CaiJingLong** [comment]
Scaffold 会被遮挡 只是自适应了大小而已

dialog你尝试增加尺寸到足够大 也会被遮挡

我考虑有没有解决方案，但是不保证一定解决，也无法承诺解决时间

在那之前可以先使用显示位置在中间来解决

**Comment by jlcool** [comment]
恩 toast 还是这个插件好点

**Comment by CaiJingLong** [comment]
在软键盘弹出时toast会移动位置到软键盘上方
更新2.1.3版本尝试是否可以解决你的问题

**Comment by li305263** [comment]
> 在软键盘弹出时toast会移动位置到软键盘上方
> 更新2.1.3版本尝试是否可以解决你的问题

2.3.2 还是会被挡住
