### ISSUE TITLE
The Toast Movement while showing.

### ISSUE THREAD

**Issue by Hermit-Alex** [OpenFlutter/flutter_oktoast#89]
Dear author,
Thank you for developing this useful package. It helps me a lot. I feel that it can add a function that if there are more than one toast showing,  the toast can change its position. Now the toast could not change its position after it was shown in the screen so that if there are more than one toast at one time , they will overlay each other.
Hope you could consider this.
Thanks 
Best wishes

**Comment by AlexV525** [comment]
Toast is a light thing, they shouldn't care about each other. If we implemented the animation for them, you'll need to customize or tweak arguments that we exposed, and at the end you may found that all of these can be controlled by yourself.
